# Generated by Django 5.0 on 2024-02-12 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalid',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='nationalid',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='nationalid',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='nationalid',
            name='profile',
        ),
        migrations.AddField(
            model_name='nationalid',
            name='appartment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='building_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='commercial_registry_office',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='father_name_full',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='floor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='ذكر', max_length=10),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='government',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='hiring_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='job_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], default='أعزب', max_length=10),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='mother_name_full',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='national_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='registry_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='religion',
            field=models.CharField(choices=[('muslim', 'مسلم'), ('christian', 'مسيحي'), ('jewish', 'يهودي')], default='مسلم', max_length=20),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='residence',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='sector',
            field=models.CharField(choices=[('other', 'أخرى'), ('private', 'قطاع خاص'), ('business', 'قطاع أعمال'), ('public', 'قطاع عام'), ('government', 'حكومة')], default="قطاع خاص'", max_length=20),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='village',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='work',
            field=models.CharField(choices=[('employed', 'يعمل'), ('unemployed', 'لا يعمل')], default='يعمل', max_length=20),
        )
    ]
