# Generated by Django 5.0 on 2024-02-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_nationalid_expiration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationalid',
            old_name='appartment_number',
            new_name='appartment',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='birth_date',
            new_name='birthdaydate',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='building_number',
            new_name='buildingNumber',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='commercial_registry_office',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='father_name_full',
            new_name='city2',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='government',
            new_name='city3',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='job_name',
            new_name='dadName',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='mother_name_full',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='residence',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='hiring_year',
            new_name='idCard',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='village',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='national_id',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='marital_status',
            new_name='socialStatus',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='phone_number',
            new_name='tradeofficeNum',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='sector',
            new_name='waywork',
        ),
        migrations.RenameField(
            model_name='nationalid',
            old_name='registry_number',
            new_name='workyear',
        ),
        migrations.AddField(
            model_name='nationalid',
            name='momName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='tradeoffice',
            field=models.CharField(default='', max_length=100),
        ),
    ]
