# Generated by Django 5.0 on 2024-02-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_national_id_alter_nationalid_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalid',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='religion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='socialStatus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='waywork',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='work',
            field=models.CharField(default='', max_length=100),
        ),
    ]
