# Generated by Django 5.0 on 2024-02-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_birthcertificate_militarystatus_personalidcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='national_id', to='base.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalIDCard',
        ),
    ]
